version: '3.2'
services:
  delivery-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-delivery
    container_name: nodejs-delivery-ctn
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/nodejs-delivery
    ports:
    - 3000:3000
    volumes:
    - .:/usr/src/node-app
    depends_on:
      - mongodb
    networks:
      - node-network
    command: npm run dev

  mongodb:
    image: mongo:4.2.1-bionic
    container_name: mongo-ctn
    volumes:
      - ./dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
